language: android

jdk:
  - oraclejdk8

env:
    global:
        - GOROOT_BOOTSTRAP=$GOROOT

before_cache:
    - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
    - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
    directories:
        - $HOME/.gradle/caches/
        - $HOME/.gradle/wrapper/

install:
    - pushd $ANDROID_HOME
    - rm -rf tools
    - wget -q https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip -O tools.zip
    - unzip -q tools.zip
    - popd
    - touch $HOME/.android/repositories.cfg
    - yes | sdkmanager
        "build-tools;27.0.3"
        ndk-bundle
        "platforms;android-27"
      >/dev/null

script:
    - ./gradlew clean goClean assembleRelease

deploy:
  provider: releases
  api_key:
    secure: d8vptvUQ/w/PXzIN9Yc6nWOHE/46dmZiz9YzADKh01q+FtngeGRMkl/v8chLPQDzxLF8NLX8IwKPYVFBiHjn5WFRrXSyI2ZYMDz23YW5FxWMIpnhI69bjfoSSeYwY0m9zWEAcbcwEEWaXdnjHLDB8NDR2BQz8qxL6ih6ouOC4v9V/ektNYkPYQtn9STjD0ZnifhU80Hj49kumnotQVA3RV89+TXColkyiWgtLW6WxcDCSgvuxMwxdHCKmwml8dusSAQpAw7gmTIrUMMN/yNoq+H4Wq4B6A7L/7xTgb/L14ohjQyl8lBE5844jOOQT82TRbExyqLZhv1hq7xDvuKhtc3BUS3NrtDS1IAdDd4k0/CLBmTLCI2+fHEWRx3Sie5TZ0x5nb6h3YrvmNNmquVj8Wm0AngRvog+Rupv6QzRQD0J8P7ieU0xV5B8IxUls1QjizIqd1Gg3nIHXPFY+WPMIxzfJrHhOxG+S6b7yK+SGpzArXYYgoLF65oxNKq1NyBTBDgFgWVh0pebNtRs47aT9EZFh1k3RVhb4ExKCXL4yFoQseW8jEqFxVt9se44r2+wDhrOiP88HUwJJEnNN6Tr5aUNlR7aSamdnzP57BU0pdwKSLHgB0W0vaniEKDteF7gpUNodgKwaqqCOXvyDXLbxvSRKcNuXtLtuZ/cJVS1iuI=
  file: "/home/travis/build/fuckshadows/fuckshadows-android/mobile/build/outputs/apk/release/mobile-universal-release.apk"
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
